analyzer:
  errors:
    public_member_api_docs: ignore
    avoid_catches_without_on_clauses: ignore
    prefer_asserts_with_message: ignore
include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    prefer_single_quotes: true
    