name: opencl
description: dart OpenCL wrapper
version: 0.2.0
repository: https://github.com/gnudles/dart_opencl

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  ffi: ^2.1.4

dev_dependencies:
  ffigen: ^19.1.0
  test: ^1.16.0
  very_good_analysis: ^9.0.0

ffigen:
  output: 'lib/src/native_cl.dart'
  headers:
    entry-points:
      - 'CL/opencl.h'
    include-directives:
      - '**cl_**.h'
      - '**cl.h'
  
  name: 'NativeCL'
  compiler-opts:
    - '-I. -DCL_TARGET_OPENCL_VERSION=300'
